FROM node:20-bullseye-slim
RUN apt-get update && apt-get install -y \
    openssl \
    libssl-dev \
    git \
    procps \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]